defmodule WeatherDotGov do
  @moduledoc """
  An API client for weather.gov,
  autogenerated from https://api.weather.gov/openapi.json
  See the documentation for information about all the functions
  available.
  """

  use WeatherDotGov.Macros
end
