# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        elixir_version: ['1.14.5', '1.15.2']
        otp_version: ['25.3.2.3', '26.0.2']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir ${{ matrix.elixir_version }}, OTP ${{ matrix.otp_version }}
      uses: erlef/setup-beam@fa5c1c242854a335722f14198649b5e8b18bc608
      with:
        elixir-version: ${{ matrix.elixir_version }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp_version }} # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Compile
      run: mix compile
    - name: Run tests
      run: mix test
